/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_jodersky_flow_internal_NativeSerial */

#ifndef _Included_com_github_jodersky_flow_internal_NativeSerial
#define _Included_com_github_jodersky_flow_internal_NativeSerial
#ifdef __cplusplus
extern "C" {
#endif
#undef com_github_jodersky_flow_internal_NativeSerial_PARITY_NONE
#define com_github_jodersky_flow_internal_NativeSerial_PARITY_NONE 0L
#undef com_github_jodersky_flow_internal_NativeSerial_PARITY_ODD
#define com_github_jodersky_flow_internal_NativeSerial_PARITY_ODD 1L
#undef com_github_jodersky_flow_internal_NativeSerial_PARITY_EVEN
#define com_github_jodersky_flow_internal_NativeSerial_PARITY_EVEN 2L
/*
 * Class:     com_github_jodersky_flow_internal_NativeSerial
 * Method:    open
 * Signature: (Ljava/lang/String;IIZI)J
 */
JNIEXPORT jlong JNICALL Java_com_github_jodersky_flow_internal_NativeSerial_open
  (JNIEnv *, jclass, jstring, jint, jint, jboolean, jint);

/*
 * Class:     com_github_jodersky_flow_internal_NativeSerial
 * Method:    readDirect
 * Signature: (JLjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_github_jodersky_flow_internal_NativeSerial_readDirect
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_github_jodersky_flow_internal_NativeSerial
 * Method:    read
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_com_github_jodersky_flow_internal_NativeSerial_read
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_github_jodersky_flow_internal_NativeSerial
 * Method:    cancelRead
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_jodersky_flow_internal_NativeSerial_cancelRead
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_jodersky_flow_internal_NativeSerial
 * Method:    writeDirect
 * Signature: (JLjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_com_github_jodersky_flow_internal_NativeSerial_writeDirect
  (JNIEnv *, jclass, jlong, jobject, jint);

/*
 * Class:     com_github_jodersky_flow_internal_NativeSerial
 * Method:    write
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_com_github_jodersky_flow_internal_NativeSerial_write
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     com_github_jodersky_flow_internal_NativeSerial
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_jodersky_flow_internal_NativeSerial_close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_jodersky_flow_internal_NativeSerial
 * Method:    debug
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_github_jodersky_flow_internal_NativeSerial_debug
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
