/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class akka_serial_sync_UnsafeSerial */

#ifndef _Included_akka_serial_sync_UnsafeSerial
#define _Included_akka_serial_sync_UnsafeSerial
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     akka_serial_sync_UnsafeSerial
 * Method:    read
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_akka_serial_sync_UnsafeSerial_read
  (JNIEnv *, jobject, jobject);

/*
 * Class:     akka_serial_sync_UnsafeSerial
 * Method:    cancelRead
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_akka_serial_sync_UnsafeSerial_cancelRead
  (JNIEnv *, jobject);

/*
 * Class:     akka_serial_sync_UnsafeSerial
 * Method:    write
 * Signature: (Ljava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_akka_serial_sync_UnsafeSerial_write
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     akka_serial_sync_UnsafeSerial
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_akka_serial_sync_UnsafeSerial_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
