/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class akka_serial_sync_UnsafeSerial__ */

#ifndef _Included_akka_serial_sync_UnsafeSerial__
#define _Included_akka_serial_sync_UnsafeSerial__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     akka_serial_sync_UnsafeSerial__
 * Method:    open
 * Signature: (Ljava/lang/String;IIZI)J
 */
JNIEXPORT jlong JNICALL Java_akka_serial_sync_UnsafeSerial_00024_open
  (JNIEnv *, jobject, jstring, jint, jint, jboolean, jint);

/*
 * Class:     akka_serial_sync_UnsafeSerial__
 * Method:    debug
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_akka_serial_sync_UnsafeSerial_00024_debug
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
