/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_jodersky_flow_UnsafeSerial__ */

#ifndef _Included_ch_jodersky_flow_UnsafeSerial__
#define _Included_ch_jodersky_flow_UnsafeSerial__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ch_jodersky_flow_UnsafeSerial__
 * Method:    open
 * Signature: (Ljava/lang/String;IIZI)J
 */
JNIEXPORT jlong JNICALL Java_ch_jodersky_flow_UnsafeSerial_00024_open
  (JNIEnv *, jobject, jstring, jint, jint, jboolean, jint);

/*
 * Class:     ch_jodersky_flow_UnsafeSerial__
 * Method:    debug
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_ch_jodersky_flow_UnsafeSerial_00024_debug
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
