/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_jodersky_flow_NativeSerial */

#ifndef _Included_com_github_jodersky_flow_NativeSerial
#define _Included_com_github_jodersky_flow_NativeSerial
#ifdef __cplusplus
extern "C" {
#endif
#undef com_github_jodersky_flow_NativeSerial_E_PERMISSION
#define com_github_jodersky_flow_NativeSerial_E_PERMISSION -1L
#undef com_github_jodersky_flow_NativeSerial_E_OPEN
#define com_github_jodersky_flow_NativeSerial_E_OPEN -2L
#undef com_github_jodersky_flow_NativeSerial_E_BUSY
#define com_github_jodersky_flow_NativeSerial_E_BUSY -3L
#undef com_github_jodersky_flow_NativeSerial_E_BAUD
#define com_github_jodersky_flow_NativeSerial_E_BAUD -4L
#undef com_github_jodersky_flow_NativeSerial_E_PIPE
#define com_github_jodersky_flow_NativeSerial_E_PIPE -5L
#undef com_github_jodersky_flow_NativeSerial_E_MALLOC
#define com_github_jodersky_flow_NativeSerial_E_MALLOC -6L
#undef com_github_jodersky_flow_NativeSerial_E_POINTER
#define com_github_jodersky_flow_NativeSerial_E_POINTER -7L
#undef com_github_jodersky_flow_NativeSerial_E_POLL
#define com_github_jodersky_flow_NativeSerial_E_POLL -8L
#undef com_github_jodersky_flow_NativeSerial_E_IO
#define com_github_jodersky_flow_NativeSerial_E_IO -9L
#undef com_github_jodersky_flow_NativeSerial_E_CLOSE
#define com_github_jodersky_flow_NativeSerial_E_CLOSE -10L
/*
 * Class:     com_github_jodersky_flow_NativeSerial
 * Method:    open
 * Signature: (Ljava/lang/String;I[J)I
 */
JNIEXPORT jint JNICALL Java_com_github_jodersky_flow_NativeSerial_open
  (JNIEnv *, jclass, jstring, jint, jlongArray);

/*
 * Class:     com_github_jodersky_flow_NativeSerial
 * Method:    read
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_com_github_jodersky_flow_NativeSerial_read
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_github_jodersky_flow_NativeSerial
 * Method:    write
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_com_github_jodersky_flow_NativeSerial_write
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_github_jodersky_flow_NativeSerial
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_jodersky_flow_NativeSerial_close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_jodersky_flow_NativeSerial
 * Method:    debug
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_github_jodersky_flow_NativeSerial_debug
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
